runtime: python39

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: dialogflow_auth.json

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
- url: /.*
  script: auto

entrypoint: python run.py