runtime: python312

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
- url: /.*
  script: auto

entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
